### PR TITLE
Migrate to GitHub Actions CI

### LINKED ISSUE #66: Migrate CI to GitHub Actions
This repo is using CircleCI today, but we'd like to revamp the CI workflows, fix any issues, and migrate to GitHub Actions.

### PR DESCRIPTION
**Pull request by cbkerr**
Migrates signac-examples to use GitHub Actions. Also upgrades the HOOMD notebook to use HOOMD version 4.

Closes #66.

### CODE REVIEW

**Comment by bdice** [comment]
@cbkerr I think this is ready to merge. Please take a look when you have a moment, but I am planning to go ahead and merge once things pass so that I can update the examples in the documentation (which has been out of date).

**Comment by bdice** [comment]
Follow-up work is already captured in issues: we need to re-enable the `flow.hoomd.lj` notebook, which still uses HOOMD 2 (see #18). Also we should complete #64 by removing or updating the other outdated tutorials.

**Comment by bdice** [comment]
Docs are updated here: https://github.com/glotzerlab/signac-docs/commit/956b2ff2047cf7d6d90f5608abf259884559d832

**Comment by cbkerr** [comment]
@bdice I had a few questions

1. Why did you choose to run all projects within the CI job as opposed to making a separate action for each test project? I guess 3 min isn't too long to wait if repeatedly testing only one of the projects.
2. What happened to fix the import error we had on early tests on the line `from mistune import BlockLexer`?

**Comment by bdice** [comment]
1. If we expand the CI matrix to include more OS or Python versions, we'd end up with way too many jobs if we have (OS x Python x Projects). I decided the runtime was fast enough, and the previous CI was designed to run in a single job so I decided to just keep it in the same design. I also wanted to take advantage of `run-tests.sh`. That script already knows which projects to run or skip via the presence of `.skipci` files, and it also knows how to detect and install any additional requirements for each project.
2. The error `ModuleNotFoundError: No module named 'mistune'` was resolved by activating the conda environment. We overlooked an "IMPORTANT" note earlier and hadn't noticed that the shell needed to be set to `shell: bash -el {0}`. https://github.com/glotzerlab/signac-examples/pull/67/commits/b54fa1b6139ea1aaedbdd0bf603a8bed84bf7af5

**Pull request merged**
